[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true # for huff foundry-huff library to access to your environment 


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
